### ISSUE TITLE
ViewComponent is looking in strange path for partials in preview

### ISSUE THREAD

**Issue by krainboltgreene** [ViewComponent/view_component#1778] opened 2023-06-21 17:58 UTC
I suspect this is due to the routing being `/rails/*`.

### Steps to reproduce
1. Define a `app/views/layout/application.html.erb` that has the expression `<%= render("head") %>`
2. Define a `app/views/application/_head.html.erb`
3. Define a preview component that uses a template

### Expected behavior
It attempts to render the template, which then attempts to render `app/views/layout/application.html.erb`, which then renders `app/views/application/_head.html.erb`.

### Actual behavior
It fails to find the partial.

**Backtrace**:
```
Missing partial view_components/_head, rails/application/_head with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :arb]}.
Searched in:
  * ".../spec/components/previews"
  * ".../app/views"
  * ".../gems/view_component-3.2.0/app/views"
  * ".../gems/railties-7.0.4.3/lib/rails/templates"
Did you mean?  application/head
               view_components/preview_source
			   ...
```

### System configuration
**Rails version**: 7.0.4.3

**Ruby version**: 3.1.2

**Gem version**: 3.2.0

**Comment by reeganviljoen** [comment] 2023-07-01 20:30
@krainboltgreene this seems hard to reproduce so could you please either create a filaing test or send a repo with the brocken behaviour

**Comment by krainboltgreene** [comment] 2023-07-01 20:31
Long weekend so yeah, I can get that done.

**Comment by reeganviljoen** [comment] 2023-09-05 06:31
@krainboltgreene any progress

**Comment by fidalgo** [comment] 2023-10-29 16:20
I've stumbled on the same error, as I had `<%= render "header" %>` in my application layout. My `_header.html.erb` lives under `views/application`, but for some reason lookbook was not able to find it.

Changing the line to `<%= render 'application/header' %>` fixed the issue.

**Comment by reeganviljoen** [comment] 2023-10-29 18:09
@krainboltgreene can you please test if this fixes your issue.

**Comment by camertron** [comment] 2023-11-03 22:52
Since we haven't gotten a response from @krainboltgreene for a while, and because @fidalgo found and kindly shared a fix for the issue (thank you!), I'm going to close this issue. Please feel free to reopen if necessary.

**Closed by camertron** 2023-11-03 22:52 UTC
Labels: help wanted
