### ISSUE TITLE
ViewComponent breaks `rails stats`

### ISSUE THREAD

**Issue by earnold** [ViewComponent/view_component#1835] opened 2023-08-30 01:15 UTC
I just discovered a small bug, where `ViewComponent` breaks running `rails stats`. [Here is a demo repo](https://github.com/earnold/view-component-error-demo). 

### Steps to reproduce
1. `rails new error-demo`
2. `cd error-demo`
3. `bundle add view_component`
4. `rails stats`

This yields the result:

```
rails aborted!
TypeError: no implicit conversion of nil into String

Tasks: TOP => stats
(See full trace by running task with --trace)
```

After some digging, I found the issue stems from [this line](https://github.com/ViewComponent/view_component/blob/main/lib/view_component/rails/tasks/view_component.rake#L10).

At this point, `ViewComponent::Base.view_component_path` resolves to `nil`.

### Expected behavior
Rails stats should work.

### Actual behavior
Rails stats throws an error

**Backtrace**:
```
/Users/evan/.rvm/gems/ruby-3.0.0/gems/railties-7.0.7.2/lib/rails/code_statistics.rb:46:in `foreach'
/Users/evan/.rvm/gems/ruby-3.0.0/gems/railties-7.0.7.2/lib/rails/code_statistics.rb:46:in `calculate_directory_statistics'
/Users/evan/.rvm/gems/ruby-3.0.0/gems/railties-7.0.7.2/lib/rails/code_statistics.rb:40:in `block in calculate_statistics'
/Users/evan/.rvm/gems/ruby-3.0.0/gems/railties-7.0.7.2/lib/rails/code_statistics.rb:40:in `map'
/Users/evan/.rvm/gems/ruby-3.0.0/gems/railties-7.0.7.2/lib/rails/code_statistics.rb:40:in `calculate_statistics'
/Users/evan/.rvm/gems/ruby-3.0.0/gems/railties-7.0.7.2/lib/rails/code_statistics.rb:21:in `initialize'
/Users/evan/.rvm/gems/ruby-3.0.0/gems/railties-7.0.7.2/lib/rails/tasks/statistics.rake:36:in `new'
/Users/evan/.rvm/gems/ruby-3.0.0/gems/railties-7.0.7.2/lib/rails/tasks/statistics.rake:36:in `block in <main>'
/Users/evan/.rvm/gems/ruby-3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/Users/evan/.rvm/gems/ruby-3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/Users/evan/.rvm/gems/ruby-3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/Users/evan/.rvm/gems/ruby-3.0.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/evan/.rvm/gems/ruby-3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/Users/evan/.rvm/gems/ruby-3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/evan/.rvm/gems/ruby-3.0.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/Users/evan/.rvm/gems/ruby-3.0.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/Users/evan/.rvm/gems/ruby-3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/evan/.rvm/gems/ruby-3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/Users/evan/.rvm/gems/ruby-3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/Users/evan/.rvm/gems/ruby-3.0.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/Users/evan/.rvm/gems/ruby-3.0.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/Users/evan/.rvm/gems/ruby-3.0.0/gems/railties-7.0.7.2/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/Users/evan/.rvm/gems/ruby-3.0.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/evan/.rvm/gems/ruby-3.0.0/gems/railties-7.0.7.2/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/Users/evan/.rvm/gems/ruby-3.0.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/Users/evan/.rvm/gems/ruby-3.0.0/gems/railties-7.0.7.2/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/evan/.rvm/gems/ruby-3.0.0/gems/railties-7.0.7.2/lib/rails/command.rb:51:in `invoke'
/Users/evan/.rvm/gems/ruby-3.0.0/gems/railties-7.0.7.2/lib/rails/commands.rb:18:in `<main>'
/Users/evan/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/Users/evan/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
```

### System configuration
**Rails version**:
Rails 7.0.7.2

**Ruby version**:
ruby 3.0.0p0

**Gem version**:
3.5.0

**Comment by boardfish** [comment] 2023-08-30 10:45
This is a duplicate of #1804, which has now been fixed and will be released in the next version of the gem.

**Closed by boardfish** 2023-08-30 10:45 UTC
