### ISSUE TITLE
Dependabot no longer shows release notes or changelog

### ISSUE THREAD

**Issue by boardfish** [ViewComponent/view_component#1503] opened 2022-08-31 09:49 UTC
### Discussed in https://github.com/github/view_component/discussions/1502

<div type='discussions-op-text'>

<sup>Originally posted by **koppen** August 31, 2022</sup>
A new ViewComponent release is a joyous event, and whenever Dependabot notifies me of one, I dig into the changelog to see what's changed.

However, the recent change to move `CHANGELOG` into `docs/` (https://github.com/github/view_component/commit/54aa0f59d06ed57bf24b1d690734c65d95c3703b / PR https://github.com/github/view_component/pull/972) seems to have broken Dependabots ability to include the changes in its pull requests. All we get now is

![CleanShot 2022-08-31 at 09 33 39](https://user-images.githubusercontent.com/6480/187619852-66f867aa-6b93-48a1-861e-4f4516e22288.png)

😢 

I miss being able to see those when Dependabot creates a Pull Request with a new release:

![CleanShot 2022-08-31 at 09 32 22](https://user-images.githubusercontent.com/6480/187619807-9b1279a8-09ab-43b0-899e-a749230c8e80.png)

Now, I didn't create this as an issue because I can't figure out if this is a Dependabot problem or a ViewComponent problem. All I know is I miss the extra signals in Dependabot PRs. What would be the best path to get those back?</div>

**Comment by boardfish** [comment] 2022-09-13 07:39
Having a little think about this – I think it's only recently that this started happening (maybe the past few versions? It's probably less than 5). I'll have a trawl through dependabot updates to see which version kicked this off.

There's every chance it could be a change in the way that Dependabot loads that information – perhaps it's rooted in #972, but I can't imagine that change caused this directly.

**Comment by boardfish** [comment] 2022-09-13 08:01
Based on Dependabot updates in a repo I'm in, I expect if this was a problem on our end it would've cropped up between v2.66 and v2.69.

**Comment by koppen** [comment] 2022-09-13 08:17
That matches what I am seeing as well. 

- 2022-08-15: Dependabot PR with a bump from 2.64.0 to 2.66.0 includes the changelog
- 2022-08-22: Dependabot PR with a bump from 2.66.0 to 2.69.0 has no changelog

The [original change I blamed](https://github.com/ViewComponent/view_component/pull/972) was [merged way before](https://github.com/ViewComponent/view_component/pull/972#event-4906668492) this on 2021-06-17.

There is nothing immediately obvious in https://github.com/ViewComponent/view_component/compare/v2.66.0...v2.69.0 that could be the cause of this, as far as I can tell. That said, I don't see anything immediately obvious in [dependabot](https://github.com/dependabot/dependabot-core/compare/v0.207.0...v0.209.0) either, but to be honest, I am not sure what I'd be looking for.

**Comment by boardfish** [comment] 2022-09-13 10:09
I think I might've cracked it - we never explicitly set `changelog_uri`. Instead, Dependabot presumably inferred it from the fact that `homepage` previously pointed to the GitHub repository. Now that `homepage` is `viewcomponent.org`, it's not working.

I don't have code in Dependabot that points to this, but I think it's a well-founded hunch that we'd probably benefit from rolling with regardless of whether it fixes this issue.

**Comment by koppen** [comment] 2022-09-13 14:15
And [this change](https://github.com/ViewComponent/view_component/commit/d28ccb6365d812779d8cbd05ea303fffa5a9efa1#diff-3e84273e5f45cd8f3f128a42fea318e775fa5f6364409602453cd08dda064965) fits the behaviour and timeline. Well done👍

**Closed** 2022-09-14 16:41 UTC

**Comment by boardfish** [comment] 2022-09-14 20:24
Thank you both for the sleuthing and quick fix, @koppen @joelhawksley!
