### ISSUE TITLE
`page` method conflict between Capybara::DSL and ViewComponent::TestHelpers

### ISSUE THREAD

**Issue by developius** [ViewComponent/view_component#1630] opened 2023-01-17 21:27 UTC
I'm getting up and running with the recently-added `with_rendered_component_path` method (cool!).

I need to write both unit tests and system tests for components, as some require JS and some don't. As such, one spec uses `with_rendered_component_path` with `visit` and one uses plain old `render_inline`.

The [testing guide for component system tests](https://viewcomponent.org/guide/testing.html#component-system-tests) doesn't yet include an example for rspec, but I _think_ I'm doing this right.

### Steps to reproduce

```ruby
# rails_helper.rb
RSpec.configure do |config|
  config.when_first_matching_example_defined(type: :component) do
    config.include ViewComponent::TestHelpers, type: :component
    config.include ViewComponent::SystemTestHelpers, type: :component
    config.include Capybara::RSpecMatchers, type: :component
    config.include Capybara::DSL, type: :component # required to use `visit` in the JS spec
  end
end
```

Write two specs - one using `with_rendered_component_path` and one without.

```ruby
RSpec.describe MyJsComponent do
  let(:component) { described_class.new }

  before do
    with_rendered_component_path(render_inline(component), layout: "admin_test") do |path|
      visit path
    end
  end

  scenario "clicking on something does something", :js do
    find("input").click
    expect(page).to have_text "test"
  end
end
```

```ruby
RSpec.describe MyComponent do
  let(:component) { described_class.new }

  it "renders some text" do
    render_inline component
    expect(page).to have_text "test"
  end
end
```

### Expected behavior
Both specs pass.

### Actual behavior
The `MyComponent` spec fails.
This is because `ViewComponent::TestHelpers` AND `Capybara::DSL` both define `page` and Capybara's version wins as it's loaded last. This breaks the spec as it needed the one from ViewComponent. Switching to `expect(rendered_component)` makes it pass, but that method is deprecated.

Is there a way to avoid including `Capybara::DSL` and access `visit` another way?

Wondering if @edwinthinks has any thoughts on this?

### System configuration
**Rails version**: 7.0.4

**Ruby version**: 3.1.2

**Gem version**: 2.81.0

**Comment by joelhawksley** [comment] 2023-01-17 22:05
@edwinthinks might you be up for reviewing this?

**Comment by edwinthinks** [comment] 2023-01-17 22:14
@joelhawksley - I think the immediate thinking for handling this is to remove the definition of `page` in the lib/view_component/system_test_case.rb and make it something that users can include when setting up VC.

Or -- perhaps remove the syntax sugar of being able to call `find`. Instead, you have to do something like `page.find`; This seems like a pretty big change that could break it for others, though.

What do you think of these two options?

**Comment by jacob-carlborg-apoex** [comment] 2023-01-24 19:54
I've not used `with_rendered_component_path` myself yet, but shouldn't specs that use `with_rendered_component_path` be system specs? Then don't include `ViewComponent::SystemTestHelpers` for component specs. Include it only for system specs. According to the documentation a system tests should inherit from `ViewComponent::SystemTestCase`, which inherits from `ActionDispatch::SystemTestCase`:

https://github.com/ViewComponent/view_component/blob/301929fe8f2a5ebaf8257f2dc355785f0d5426e2/lib/view_component/system_test_case.rb#L6

According to the RSpec documentation system specs are wrappers around Rails' system tests, which are inherited from `ActionDispatch::SystemTestCase`.

**Comment by edwinthinks** [comment] 2023-01-24 21:55
Ahh thats a good point @jacob-carlborg-apoex ; Could you try @developius to selectively include:
```
ViewComponent::SystemTestHelpers
```
and/or
```
Capybara::DSL
```

To be on system or browser type tests and see if that works?

**Comment by developius** [comment] 2023-01-26 04:04
@jacob-carlborg-apoex that is a good point. I was hoping to be able to use both forms of test in the same file, like we can with feature specs with the `:js` flag. Splitting up the spec into `spec/components` and `spec/features/components` feels a little weird, but I understand that one set is running system specs and the other is unit specs. Would be nice if we could configure either setup though.

@edwinthinks  I tried this but it doesn't work, it seems to ignore the `js` metadata. Maybe I'm not using it correctly?:

```ruby
config.include ViewComponent::TestHelpers, type: :component, js: false
config.include ViewComponent::SystemTestHelpers, type: :component, js: true
config.include Capybara::DSL, type: :component, js: true
config.include Capybara::RSpecMatchers, type: :component, js: true
```

**Comment by jacob-carlborg-apoex** [comment] 2023-01-26 08:06
> I was hoping to be able to use both forms of test in the same file, like we can with feature specs with the :js flag.

Component specs are more similar to view specs than to system specs. Component specs and view specs just contain a string with the rendered content. A system spec consists of some form of browser that supports navigation. You cannot navigate to a page in view or component specs.

> I tried this but it doesn't work, it seems to ignore the js metadata. Maybe I'm not using it correctly?

I don't know how `config.include` works with tags, but when passing multiple tags on the command line it means "or", not "and". Might be the same with `config.include`.

**Comment by developius** [comment] 2023-01-26 09:09
Thanks for the suggestion @jacob-carlborg-apoex, but unfortunately I can't get that to work either.

Not the end of the world, I don't see a problem with separating the two types of spec in the way we normally do with other kinds of specs. Or, alternatively asserting on the result of `render_inline` instead of `page`.

I'm happy to open a PR adding example usage for rspec with`with_rendered_component_path` unless you feel better positioned to do that @edwinthinks?

**Comment by edwinthinks** [comment] 2023-01-26 15:04
Upon closer inspection, it is caused by https://github.com/ViewComponent/view_component/blame/9c5a9c7727b6186ece8b86fb832e7f6fd969580a/lib/view_component/test_helpers.rb#L11 or at least related to this. The errors I'm seeing are that its trying to call `visit` on the `Capybara::Node::Simple` 

I want to think about how we can make this work in a more elegant fashion without having to resort to overriding and adding excessive changes. However, here is the approach I was able to use to avoid the issue:

Use a different tag for component tests using JS; in rails helper
```
  config.include ViewComponent::SystemTestHelpers, type: :component_js

  config.before(:each, type: :component_js) do
    def page
      # Overrides the Capybara overwrite.
      Capybara.current_session
    end
  end
```

Then in your tests, use the tags system & component_js
```
Spec.describe ExampleComponent, type: [:system, :component_js] do
  let(:component) { described_class.new }

  before do
    with_rendered_component_path(render_inline(component)) do |path|
      visit path
    end
  end

  scenario "clicking on something does something", :js do
    find("input").click
    expect(page).to have_text "test"
  end
end
```
 
Not my ideal way to make this work, I'm curious to know how we can possibly refactor view components to avoid this collision.

**Comment by joelhawksley** [comment] 2023-04-04 20:42
While I like the idea of having a single file that mixes multiple test types, I don't think that would align well with standard Rails practices. I don't think the ergonomics of this proposal outweigh that inconsistency, so I'm going to close this issue ❤️

**Closed by joelhawksley** 2023-04-04 20:42 UTC

**Comment by developius** [comment] 2023-04-04 20:52
Fair enough @joelhawksley, thanks for the consideration.
